version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:4.0.6
    ports:
      - '6379:6379'
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'pantry_management'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: